# Generated by Django 3.1.7 on 2021-06-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(default='unisex', max_length=6),
            preserve_default=False,
        ),
    ]
