# Generated by Django 3.1.7 on 2021-06-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_auto_20210602_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='clothes_type',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
